version: "3.4"
services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0